version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=1h
    volumes:
      - ollama_data:/root/.ollama
  api:
    image: python:3.9-slim
    container_name: fastapi-api
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn api:app --host fanato-ai-server.sit.kmutt.ac.th --port 8001"
    environment:
      - USE_TGI=false
      - USE_VLLM=false
      - MODEL_NAME=AdaptLLM/finance-chat
    ports:
      - "8001:8001"
    depends_on:
      - ollama

volumes:
  ollama_data:
